### PR TITLE
Task1: Google page

### PR DESCRIPTION
**Pull request by tkachdmytro**

### CODE REVIEW

**Comment by maxkharena** [comment]
Use your Github username as folder's name.

**Review by maxkharena — COMMENTED** [review]
Change tag center this feature has been removed from the Web standards
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

**Review by denysdovhan — CHANGES_REQUESTED** [review]
Please, fix your solution!

**Comment by tkachdmytro** [comment]
Виправив

**Pull request merged**
